### ISSUE TITLE
Experiment on Jatos

### ISSUE THREAD

**Issue by konstantinamgt** [BonnieMcLean/IcoTools#10]
Hello,

Thank you very much for the code, very useful! I am wondering if you ever used Jatos, as I am trying to upload the experiment (html, csv, php, audio files) there. I run into trouble when running the html file from the Jatos server, as it doesn't play the sounds anymore. Any help would be welcome:) 

Thank you!
Best,
Konstantina

**Comment by konstantinamgt** [comment]
Hello again,

I've worked on it and managed to upload the experiment on the Jatos server. I now run into two problems:
- the audio files can't be played when running the experiment online (the audio files are stored on a public repository on GitHub)
- when I run one of your experiments on the Jatos server, the PHP file at the end cannot be found, thus the answers can't be stored

Let me know if you need more details or anything else !

Thank you very much !
Konstantina

**Comment by BonnieMcLean** [comment]
Hi Konstantina,

Thanks for trying out my code and I'm sorry you're running into some problems. I haven't used Jatos before, but one thing that would be useful to know is when you run the experiment online, if you right click and press 'inspect', what error messages do you get? If you want, it might be easier to video call then you can share your screen with me and I might be able to figure out what is going wrong. If you want to try that you can send me an email to bonnie.mclean@lingfil.uu.se and we can organise a time to meet.
